<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

	<div id="header">
		
	<!--Menu Superior-->
			
		<ul id="topmenu">
			<li>|<a href="descripcion_app.php"> Descripción </a>|</li>
			<li><a href="#"> About us </a>|</li>
		</ul>
		
	<!--Menu Principal-->	
		
	<div id="menu">
		<ul id="navegador" >
			<li><a href="index.php">INICIO</a></li>
			<li><a href="feed.php">NOVEDADES</a></li>
			<li id="desplegable"><a href="#">COMICS</a>
					<ul id="subnavegador"  >
					<li><a href="americano.php">AMERICANO</a></li>
					<li><a href="dc.php">DC</a></li>
					<li><a href="europeo.php">EUROPEO</a></li>
					<li><a href="manga.php">MANGA</a></li>
					<li><a href="marvel.php">MARVEL</a></li>
					</ul></li>
			<li><a href="contacto.php">CONTACTO</a></li>	
						
			</ul>
		</div>
		
				
	<!--Barra separadora-->		
		
	</div>	
	<div class="separador">
	</div>
	