<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

	<!-- Importa el css que se necestia en la mayoria de las páginas -->	
	
	<link rel="stylesheet" href="css/style.css" type="text/css">
	<link rel="stylesheet" href="css/noticias.css" type="text/css">
	<link rel="stylesheet" href="css/menu.css" type="text/css">
	<link rel="stylesheet" href="css/login.css" type="text/css"> 
	<link rel="stylesheet" href="css/errores.css" type="text/css"> 
	<link rel="stylesheet" href="css/topventas.css" type="text/css" >
	<link rel="stylesheet" href="css/formularioBusqueda.css" type="text/css" >
	<link rel="stylesheet" href="css/carrito.css" type="text/css" >

	<!-- Importa el javascript que se necestia en la mayoria de las páginas -->

   	<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
   	<script type="text/javascript" src="javascript/noticias.js"></script>
   	<script type="text/javascript" src="javascript/menu.js"></script>
   	<script type="text/javascript" src="javascript/login.js"></script>
   	