<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

	<!-- Menu de noticias interactivo-->
	
	<div id="noticias">
			<a href="#" id="anterior" ></a>
			<a href="#" id="siguiente"></a>
			<ul>
				<li><a href="#" ><img src="./media/producto1.jpg" title="Producto 1" alt="Producto 1"></a></li>
				<li><a href="#" ><img src="./media/producto2.jpg" title="Producto 2" alt="Producto 2"></a></li>
				<li><a href="#" ><img src="./media/producto3.jpg" title="Producto 3" alt="Producto 3"></a></li>
			</ul>
	</div>
		